dist: trusty
language: java
addons:
  firefox: 58.0.1
before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
    - tar -xzf geckodriver-v0.19.1-linux64.tar.gz
    - whereis geckodriver
script:
  - mvn verify -Dwebdriver="firefox" -Dwebdriver.headless="1"